import re
import pytest

def python_parse_gcode(gcode_text: str):
    """
    Python mirror of frontend/js/parsers/gcode.js to ensure regression prevention
    and strict parity for slicer metadata extraction.
    """
    print_time_seconds = 0
    filament_grams = 0
    filament_type = None

    lines = gcode_text.splitlines()
    candidate_lines = lines[:500] + lines[-500:]

    for raw_line in candidate_lines:
        line = raw_line.strip()
        if not line.startswith(";"):
            continue

        if any(k in line.lower() for k in ["estimated printing time", "print time", "build time", "total time"]):
            hhmmss = re.search(r"(?:=|\:)\s*(\d+):(\d+):(\d+)", line)
            if hhmmss:
                h, m, s = int(hhmmss.group(1)), int(hhmmss.group(2)), int(hhmmss.group(3))
                calculated = (h * 3600) + (m * 60) + s
                if calculated > 0:
                    print_time_seconds = calculated
            else:
                d_match = re.search(r"(\d+)\s*d(?:ays?)?", line, re.I)
                h_match = re.search(r"(\d+)\s*h(?:ours?|r)?", line, re.I)
                m_match = re.search(r"(\d+)\s*m(?:in(?:ute)?s?)?", line, re.I)
                s_match = re.search(r"(\d+)\s*s(?:ec(?:ond)?s?)?", line, re.I)
                if d_match or h_match or m_match or s_match:
                    days = int(d_match.group(1)) if d_match else 0
                    hours = int(h_match.group(1)) if h_match else 0
                    mins = int(m_match.group(1)) if m_match else 0
                    secs = int(s_match.group(1)) if s_match else 0
                    calculated = (days * 86400) + (hours * 3600) + (mins * 60) + secs
                    if calculated > 0:
                        print_time_seconds = calculated

        cura_time = re.search(r"^;TIME:\s*(\d+)", line, re.I)
        if cura_time and not print_time_seconds:
            print_time_seconds = int(cura_time.group(1))

        if re.search(r"filament used\s*\[g\]", line, re.I):
            numbers = re.findall(r"[0-9]+(?:\.[0-9]+)?", line)
            if numbers:
                total_g = sum(float(n) for n in numbers)
                if total_g > 0:
                    filament_grams = total_g

        cura_weight = re.search(r"filament (?:weight|used)\s*[:=]\s*([0-9.]+)\s*g?", line, re.I)
        if cura_weight and not filament_grams and "[mm]" not in line and "[m]" not in line:
            filament_grams = float(cura_weight.group(1))

        mat_match = re.search(r"filament_type\s*=\s*([A-Za-z0-9_-]+)", line, re.I)
        if mat_match:
            filament_type = mat_match.group(1).strip()

    hours = round(print_time_seconds / 3600.0, 2) if print_time_seconds > 0 else 0.0
    return {
        "print_time_hours": hours,
        "part_weight_g": round(filament_grams, 2),
        "filament_type": filament_type,
    }


def test_prusa_slicer_gcode_parsing():
    sample = """
; generated by PrusaSlicer 2.7.1 on 2026-03-10
; filament_type = PETG
; filament used [mm] = 4520.3
; filament used [cm3] = 10.87
; filament used [g] = 32.50
; estimated printing time (normal mode) = 2h 15m 30s
G21
G90
M107
    """
    res = python_parse_gcode(sample)
    # 2h 15m 30s = 8130 seconds = 2.26 hours
    assert res["print_time_hours"] == 2.26
    assert res["part_weight_g"] == 32.50
    assert res["filament_type"] == "PETG"


def test_prusa_multi_material_gcode_parsing():
    sample = """
; generated by PrusaSlicer MMU
; filament_type = PLA
; filament used [g] = 14.20, 8.50, 3.10
; estimated printing time (normal mode) = 1h 45m
    """
    res = python_parse_gcode(sample)
    # 14.2 + 8.5 + 3.1 = 25.80 g
    assert res["part_weight_g"] == 25.80
    assert res["print_time_hours"] == 1.75
    assert res["filament_type"] == "PLA"


def test_cura_gcode_parsing():
    sample = """
;FLAVOR:Marlin
;TIME:5400
;Filament used: 42.1g
;Generated with Cura_SteamEngine 5.4.0
M140 S60
    """
    res = python_parse_gcode(sample)
    # 5400 seconds = 1.5 hours
    assert res["print_time_hours"] == 1.50
    assert res["part_weight_g"] == 42.10


def test_hh_mm_ss_format_gcode_parsing():
    sample = """
; total time: 03:30:00
; filament used [g] = 50.0
    """
    res = python_parse_gcode(sample)
    assert res["print_time_hours"] == 3.50
    assert res["part_weight_g"] == 50.0
